Switch from Yarn to pnpm (#379)
* Update installation command

* Update to pnpm commands

* Change github workflow

* Delete cache in GH workflow

* Update to pnpm

* Update docker and scripts to pnpm

* Add package-size.yml solution

* Add hoisting, domhandler, allowJS

* Delete hoisting, add overrides in package.json

* Change github workflow testing command

* Change overrides in package.json

* Add pnpm tsc to gh actions yaml

* Update overrides, delete pnpm tsc

* Remove @next/eslint-plugin-next

* Change overrides

* Change overrides path to tsdx/**/

* Revert overrides changes

* Switch eslint-config-upleveled

* Edit overrides

* Delete allowJS from tsconfig

* Update pnpm-lock

* Add 2nd tsconfig

* Work around tsdx build error TS2347

(typescript) Error: /Users/k/p/preflight/src/checks/noDependencyProblems/noDependenciesWithoutTypes.ts(62,29): semantic error TS2347: Untyped function calls may not accept type arguments.

Ref: https://github.com/upleveled/preflight/actions/runs/4697605804/jobs/8328868483

* Fix linting errors

* Update module and target

* Separate steps

* Exclude files

* Pass arguments to underlying command

* Update src/checks/useSinglePackageManager.ts

Co-authored-by: Karl Horky <karl.horky@gmail.com>

* Remove yarn from the error message

* Add pnpm cache, pnpm install to gh workflow

* Switch to shamefully-hoisted=true

* Revert changes to use node-linker=hoisted

* Update pnpm-lock file

* Switch docker workflow order

* Delete white space

* Update to new Upleveled ESLint url

* Add logging

* Update prettier.ts

* Try --silent

* Update prettier.ts

* Update prettier.ts

* Use path to Prettier bin

* Fix path

* Update src/checks/useSinglePackageManager.ts

---------

Co-authored-by: Karl Horky <karl.horky@gmail.com>